svrxjs/svrx

packages/svrx-cli/bin/svrx.js
packages/svrx-cli/lib/config.js
packages/svrx-cli/lib/index.js
packages/svrx-cli/package-lock.json
packages/svrx-cli/package.json
packages/svrx-plugin-webpack/package-lock.json
packages/svrx-toolkit/package-lock.json
packages/svrx-ui/package-lock.json
packages/svrx-util/lib/rc-file-read.js
packages/svrx-util/lib/svrx-util.js
packages/svrx-util/package-lock.json
packages/svrx-util/package.json
packages/svrx/lib/svrx.js
packages/svrx/package-lock.json
packages/svrx/package.json

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) feature
* **Does this PR introduce a breaking change?**  no

feat(cli): add global rc config

---

packages/svrx/package.json

fix(core): #18 , `https` not working

---

packages/svrx/lib/injector/index.js

* **What kind of change does this PR introduce?** 
bugfix:
- 插件client端无法正确显示中文
- 插件client端字符解析报错

fix(io): set charset for injected script

---

packages/svrx-util/lib/rc-file-read.js
packages/svrx/__tests__/spec/svrx.configure.js
packages/svrx/lib/config-list.js
packages/svrx/lib/configure/index.js
packages/svrx/lib/configure/option.js
packages/svrx/lib/configure/plugin.js

test(config): add testcases

---

packages/svrx/__tests__/spec/svrx.plugin.js
packages/svrx/lib/plugin/system.js

Add plugin version match check

---

packages/svrx/__tests__/fixture/plugin/svrx-plugin-depend/index.js
packages/svrx/__tests__/fixture/plugin/svrx-plugin-test/index.js
packages/svrx/__tests__/spec/svrx.configure.js
packages/svrx/__tests__/util.js
packages/svrx/lib/configure/index.js
packages/svrx/lib/configure/plugin.js

Fix config.get() to get all default values

---

packages/svrx/__tests__/spec/svrx.plugin.js
packages/svrx/lib/plugin/svrx-plugin-open/index.js

feat(open): support relative path to open

---

packages/svrx/lib/constant.js
packages/svrx/lib/plugin/svrx-plugin-serve/index.js
packages/svrx/lib/svrx.js

Fix router not work when historyfallback set to true

---

packages/svrx/__tests__/spec/svrx.configure.js
packages/svrx/lib/configure/index.js

Fix parse plugin querystring with dot string

---

packages/svrx-util/lib/logger.js
packages/svrx/__tests__/spec/svrx.plugin.js
packages/svrx/lib/plugin/loader.js
packages/svrx/lib/plugin/npm.js
packages/svrx/lib/plugin/svrx-plugin-open/index.js
packages/svrx/lib/plugin/system.js
packages/svrx/lib/plugin/task.js

Multiple install

---

.gitignore
.travis.yml
package-lock.json
package.json
packages/svrx-util/package.json
packages/svrx/lib/plugin/npm.js
packages/svrx/package.json

Add codecov support

---

LICENSE
README.md
codecov.yml

Add license and badges

---

packages/svrx/__tests__/spec/svrx.base.js
packages/svrx/lib/injector/index.js
packages/svrx/lib/io/index.js
packages/svrx/lib/middleware/index.js
packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
packages/svrx/lib/plugin/svrx-plugin-serve/index.js
packages/svrx/lib/plugin/system.js
packages/svrx/lib/svrx.js
packages/svrx/lib/util/helper.js

- support middleware.add onRoute and change all onCreate usage to onRoute
- middleware coverage to 100%
- support dynamic updating (for reload feat in future)
feature
none
no, downward compatibility with onCreate

Middleware route

---

packages/svrx/__tests__/spec/svrx.plugin.proxy.js
packages/svrx/lib/plugin/npm.js

Add testcases for plugin proxy

---

CHANGELOG.md
lerna.json
packages/svrx-util/package-lock.json
packages/svrx-util/package.json
packages/svrx/package-lock.json
packages/svrx/package.json

Publish v0.0.7

---

packages/svrx-util/__tests__/spec/npm.test.js
packages/svrx-util/lib/npm/index.js
packages/svrx/lib/plugin/npm.js

Return the right package info after npmi

---

CHANGELOG.md
LICENSE
README.md
lerna.json
packages/svrx-util/package.json
packages/svrx/lib/svrx.js
packages/svrx/package.json

- [] Tests for the changes have been added (for bug fixes / features)          
internal
no
transfer repo from x-orpheus

Rename every 'x-orpheus' to 'svrxjs'

---

.travis.yml
lerna.json
packages/svrx-util/README.md
packages/svrx-util/npm-shrinkwrap.json
packages/svrx-util/package.json
packages/svrx/lib/configure/index.js
packages/svrx/lib/configure/pluginInfo.js
packages/svrx/lib/plugin/npm.js
packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
packages/svrx/lib/plugin/svrx-plugin-serve/index.js
packages/svrx/lib/svrx.js
packages/svrx/lib/util/logger.js
packages/svrx/npm-shrinkwrap.json
packages/svrx/package.json

internal
no
- set npm scope to `@svrx`
- rename packages in docs
- published v1.0

Change npm  publish scope

---

.travis.yml

chore: test on node v12

---

npm-shrinkwrap.json
packages/svrx-util/npm-shrinkwrap.json
packages/svrx/npm-shrinkwrap.json

chore: fix package version lock

---

lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

publish v1.0.3

---

packages/svrx/lib/router/loader.js

fix: routing update not working

---

packages/svrx-util/lib/npm/index.js

Prevent modify package.json when plugin installation

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md

Add content to readme

---

lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

chore(release): publish v1.0.5-beta.0

---

lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

chore(release): publish v1.0.5

---

CHANGELOG.md

Add changelog for 1.0.5

---

packages/svrx/lib/plugin/svrx-plugin-livereload/assets/index.js

fix: livereload client error

---

CHANGELOG.md
lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

publish v1.0.6

---

CHANGELOG.md
lerna.json
package.json
packages/svrx-util/package.json
packages/svrx/package.json

chore(release): publish v1.1.0

---

packages/svrx-util/__tests__/fixture/.svrx/config/.svrxrc.js
packages/svrx-util/__tests__/fixture/.svrx/versions/1.0.6/package.json
packages/svrx-util/__tests__/spec/package-manager.test.js
packages/svrx-util/__tests__/spec/rc-file-read.test.js
packages/svrx-util/lib/c2k.js
packages/svrx-util/lib/package-manager/index.js
packages/svrx-util/lib/package-manager/package-manager.js
packages/svrx/lib/config-list.js
packages/svrx/lib/util/jsonSchemaDefaults.js

feature
no
- support core package installation and info get
- add `remove` func
- add testcases

Support svrx-cli for core package installation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

build: perf the pr and issue templates

---

package.json
packages/svrx/package.json

Update lerna and path-to-regex

---

CHANGELOG.md
lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

Update to 1.1.1

---

packages/svrx-util/__tests__/spec/package-manager.test.js
packages/svrx-util/lib/package-manager/package-manager.js

1. enable auto clean on local package load

Enable auto clean on local package load

---

packages/svrx-util/__tests__/spec/package-manager.test.js
packages/svrx-util/lib/package-manager/package-manager.js

1. Before this PR, auto update package will block package load, so we lower the priority

Put auto update package after local package load

---

.travis.yml
packages/svrx-util/__tests__/spec/package-manager.test.js
packages/svrx-util/package.json
packages/svrx/__tests__/spec/configure/inline.js
packages/svrx/__tests__/spec/svrx.base.js
packages/svrx/__tests__/spec/svrx.plugin.js
packages/svrx/__tests__/spec/svrx.router.js
packages/svrx/package.json

Add multi os test

---

CHANGELOG.md
lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

1. Publish 1.1.4 of svrx and util

Publish v1.1.4

---

packages/svrx-util/package.json

build: update global-npm@0.4.1 to fix "cannot find npm error" in npm script
https://github.com/dracupid/global-npm/issues/5
1.
1.

build: update global-npm@0.4.1 to fix "cannot find npm error"

---

CHANGELOG.md
lerna.json
packages/svrx-util/package.json
packages/svrx/package.json

chore(release): publish v1.1.5

---

README.md
README.zh-CN.md

docs: add some feature detail and README.zh-CN.md

---

.github/workflows/cov.yml
.github/workflows/testOnLinux.yml

build: change actions default branch

---

.github/workflows/cov.yml
.github/workflows/release.yml
.github/workflows/testOnLinux.yml
packages/svrx/__tests__/spec/svrx.base.js
packages/svrx/package.json

build: edit actions configs

---

.github/workflows/testOnLinux.yml
.github/workflows/testOnMac.yml
.github/workflows/testOnWin.yml

build: add mac and wondows for test

---

.github/workflows/release.yml
CHANGELOG.md
lerna.json
package.json
packages/svrx-util/package.json
packages/svrx/package.json

chore(release): publish v1.1.6

---

CHANGELOG.md
lerna.json
packages/svrx-util/lib/package-manager/package-manager.js
packages/svrx-util/package.json
packages/svrx/package.json

fix(util): fix install error on Windows
